INSERT INTO public.configuracoes (chave, valor)
VALUES (
  'sectors',
  '["CALDEIRARIA","ELÉTRICA E INSTRUMENTAÇÃO","GERAÇÃO DE ENERGIA","GERAÇÃO DE VAPOR","HIDROJATO","LABORATÓRIO E PCTS","MECÂNICA, LUBRIFICAÇÃO E USINAGEM","PCM","PCTS","PRODUÇÃO DE ÁLCOOL","RPE","SERVIÇOS ADMINISTRATIVOS","TRATAMENTO DE ÁGUA - ETA","TRATAMENTO DO CALDO"]'
)
ON CONFLICT (chave) DO NOTHING;